SELECT NAME, DATEDIFF(month, START_DATE, FINISH_DATE ) AS MONTH_COUNT
FROM CLIENT 
JOIN PROJECT ON CLIENT_ID = CLIENT.ID
GROUP BY NAME, START_DATE 
HAVING MAX(MONTH_COUNT) IN (SELECT MAX(MONTH_COUNT) FROM  PROJECT);