SELECT PROJECT.ID AS PROJECT, CLIENT.NAME, (DATEDIFF(month, START_DATE, FINISH_DATE ) * SUM(SALARY)) AS PRICE  
FROM CLIENT 
JOIN PROJECT ON CLIENT_ID = CLIENT.ID
JOIN PROJECT_WORKER ON PROJECT_ID = PROJECT.ID 
JOIN WORKER ON WORKER_ID = WORKER.ID
GROUP BY PROJECT.ID